### PR TITLE
Set RollingUpdate default for deployment

### PR DESCRIPTION
**Pull request by razum2um**
Discussion started here  https://github.com/mattermost/mattermost-helm/issues/174

### CODE REVIEW

**Comment by cpanato** [comment]
@razum2um please sign the CLA
thanks!

**Comment by razum2um** [comment]
@cpanato done

**Review by jwilander — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Comment by jwilander** [comment]
Thanks @razum2um !

**Pull request merged**
