### PR TITLE
Add extraVolumes and Mounts

### PR DESCRIPTION
**Pull request by s3than**
#### Summary
Adds the ability to implement volumes and mounts from the values file see: https://github.com/mattermost/mattermost-helm/issues/124

Functionality was ported from the enterprise edition

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-helm/issues/124

### CODE REVIEW

**Comment by jasonblais** [comment]
@cpanato friendly reminder to help with a review :) (cc @stylianosrigas)

**Comment by s3than** [comment]
@stylianosrigas @cpanato I want to thank you for the Mug.. it does have the wrong name on it though :smiley: All good thank you again hope you are all safe in these times. TC

**Comment by jasonblais** [comment]
> it does have the wrong name on it though

@s3than Oh no :( Do you have an account on community.mattermost.com? If so, would you be open to reaching out to `@hanna.park` on the server and she can get that resolved.

**Comment by cpanato** [comment]
@s3than oh no! please follow what Jason said

**Comment by s3than** [comment]
@cpanato Reached out on community.mattermost these things happen 😊

**Pull request merged**
