### PR TITLE
Add nodeSelector support for helm chart

### PR DESCRIPTION
**Pull request by FlipEnergy**
#### Summary
Adding support to specify nodeSelector, affinity and tolerations for deployments/pods.

#### Ticket Link
N/A

### CODE REVIEW

**Comment by jaydeland** [comment]
@stylianosrigas @jwilander any idea if this is a new error in linting:
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
Error linting charts: Error initializing Helm: Error waiting for process: exit status 1

**Comment by stylianosrigas** [comment]
> @stylianosrigas @jwilander any idea if this is a new error in linting:
> Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
> Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
> Error linting charts: Error initializing Helm: Error waiting for process: exit status 1

@jaydeland This stable repo is deprecated and replaced by `https://charts.helm.sh/stable`

**Comment by jaydeland** [comment]
oh - I see @FlipEnergy can you merge the latest code from master into your branch?

**Comment by FlipEnergy** [comment]
> 
> 
> oh - I see @FlipEnergy can you merge the latest code from master into your branch?

Hm, my branch appears to be only 1 commit on top of the latest master (commit 6906a2126a931a000edc15bc403203ee6cf15835) so it is up to date. I did double check by pulling and such.

**Comment by jaydeland** [comment]
> > oh - I see @FlipEnergy can you merge the latest code from master into your branch?
> 
> Hm, my branch appears to be only 1 commit on top of the latest master (commit [6906a21](https://github.com/mattermost/mattermost-helm/commit/6906a2126a931a000edc15bc403203ee6cf15835)) so it is up to date. I did double check by pulling and such.

oh sorry - I can see that tests/ct.yml has the correct updated stable repo on master and assumed that was the problem.

**Comment by khos2ow** [comment]
> Hm, my branch appears to be only 1 commit on top of the latest master (commit [6906a21](https://github.com/mattermost/mattermost-helm/commit/6906a2126a931a000edc15bc403203ee6cf15835)) so it is up to date.

You are correct @FlipEnergy, but since then and now Helm 2.x, which is being used in `quay.io/helmpack/chart-testing:v2.4.1` has been fully deprecated, you can bump the `chart-testing` version to `v3.3.1` and give it another go.

**Comment by khos2ow** [comment]
Ok, new error, that's good!

**Review by khos2ow — CHANGES_REQUESTED** [review]
@FlipEnergy I've fixed the failing CI, can you please rebase on master? (you should effectively revert https://github.com/mattermost/mattermost-helm/pull/204/commits/75b335b946509974a62759ed1572cbb0e180d940)

**Review by khos2ow — COMMENTED** [review]
Thanks @FlipEnergy, please also add the same support to `mattermost-enterprise-edition` chart as well and we should be good to go.

**Review by khos2ow — APPROVED** [review]
Thank you @FlipEnergy, LGTM!

**Comment by FlipEnergy** [comment]
Thanks all!

**Pull request merged**
