### PR TITLE
Add DNSConfig customization ability to RTCD service chart

### PR DESCRIPTION
**Pull request by stafot**
Issue: CLD-3730
Signed-off-by: Stavros Foteinopoulos <stafot@gmail.com>

#### Summary
Add DNSConfig customization ability to RTCD service chart

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-3730

### CODE REVIEW

**Comment by streamer45** [comment]
Not sure what's the impact of this but to share some context, from the plugin side we currently run a resolution on the rtcd host every 10 seconds to check if new hosts came up/went down in order to support horizontal scaling.

**Review by streamer45 — APPROVED** [review]
> @streamer45 Yeap, this lookup every 10 seconds with the default `ndots` configuration which defaults to 5 on kubernetes, creates 10 queries while it should need only 2 if we have the optimized setting for `ndots` which is 1. To be able to parameterize this configuration we need the field this PR adds. I can provide more details if you are interested.

Thanks for the context Stavros, makes sense :+1:

**Comment by phoinixgrr** [comment]
🎖️  Works fine. Great work 👍 

Non blocking recommendation following: 
If we interested in automatically generating README file, documenting the chart values, their defaults, and an optional description parsed from comments, worth taking a  looking at https://github.com/norwoodj/helm-docs

Low hanging fruit 🥝 🍌 🍒

**Review by phoinixgrr — APPROVED** [review]

**Comment by stafot** [comment]
@phoinixgrr Totally agree, let's create a ticket for this I am more than happy to work on this.

**Pull request merged**
