### PR TITLE
Fix mysql fields

### PR DESCRIPTION
**Pull request by keremavci**

### CODE REVIEW

**Comment by jasonblais** [comment]
@keremavci Would you be open to help complete the Mattermost [contribution license agreement (CLA)](http://www.mattermost.org/mattermost-contributor-agreement/)? Once you have signed, we can start the review process.

Let us know if you have any questions about the CLA, we'd be happy to answer any you may have.

**Comment by jfrerich** [comment]
Thanks for the PR, @keremavci!  Could you resolve the failing build issues.  If you have any questions, please feel free to message one of the PR reviewers.

**Comment by emilyacook** [comment]
> > Thanks for the PR, @keremavci! Could you resolve the failing build issues. If you have any questions, please feel free to message one of the PR reviewers.
> 
> You're welcome. I guess build issues happened due to the chart version. I increased the version but the lint step got a different error. Could you please check it?

Hi @stylianosrigas @angeloskyratzakos, would one of you mind looking into this?

**Comment by stylianosrigas** [comment]
> > > Thanks for the PR, @keremavci! Could you resolve the failing build issues. If you have any questions, please feel free to message one of the PR reviewers.
> > 
> > 
> > You're welcome. I guess build issues happened due to the chart version. I increased the version but the lint step got a different error. Could you please check it?
> 
> Hi @stylianosrigas @angeloskyratzakos, would one of you mind looking into this?

Hi @keremavci and thanks for the PR. We had some fixes lately in our build pipelines and this is why its failing I guess. Can you please rebase and push? It should fix it.

**Comment by stylianosrigas** [comment]
@keremavci Thank you for fixing the the tests on your end. From what I understand you want to be able to specify the mysql dependency chart tag and repo. Your change will not affect that considering that the mysql is a requirement and its repo/image is specified in the requirements.yaml file. The change you suggested is not going to solve your problem unless its propagated in this file.

**Comment by keremavci** [comment]
> @keremavci Thank you for fixing the the tests on your end. From what I understand you want to be able to specify the mysql dependency chart tag and repo. Your change will not affect that considering that the mysql is a requirement and its repo/image is specified in the requirements.yaml file. The change you suggested is not going to solve your problem unless its propagated in this file.

Hi,
The "repository" keyword is wrong. I think It should be "image".
Can you please check https://github.com/helm/charts/tree/master/stable/mysql#configuration

**Comment by stylianosrigas** [comment]
> > @keremavci Thank you for fixing the the tests on your end. From what I understand you want to be able to specify the mysql dependency chart tag and repo. Your change will not affect that considering that the mysql is a requirement and its repo/image is specified in the requirements.yaml file. The change you suggested is not going to solve your problem unless its propagated in this file.
> 
> Hi,
> The "repository" keyword is wrong. I think It should be "image".
> Can you please check https://github.com/helm/charts/tree/master/stable/mysql#configuration

@keremavci Hello and sorry for the delay in the response. What I mean is that these repository and imageTag entries are of no use in the current helm chart. Changing the value name won't have any affect because the default values of they mysql stable chart are used every time. These entries should be removed as it is misleading having them there.

**Comment by lindy65** [comment]
Hi @keremavci - I'm helping to review stale PRs and, since we haven't heard from you in a few months, I'll close this PR for now. Please feel free to re-open if you're able to prioritize. Thanks!

//cc @stylianosrigas @angeloskyratzakos

**Pull request closed without merging**
