### PR TITLE
update chart to be GitOps ready

### PR DESCRIPTION
**Pull request by RenePinnow**
#### Summary

- give the option to overwrite random string from configmap else applications like argocd will infinity sync because there always a diff

- give the option to provide secrets from external because storing secret data like passwords in git is an anti pattern. 

- remove replicas if ha is enabled. The number of replicas is calculate by hpa else there is a diff between git and the cluster state.

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-helm/issues/261

### CODE REVIEW

**Comment by RenePinnow** [comment]
@cpanato Conflicts are solved.

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @RenePinnow

**Comment by RenePinnow** [comment]
@cpanato 
Why was this never merged?

**Comment by cpanato** [comment]
> @cpanato Why was this never merged?

there is a conflict that needs to be addressed

**Comment by RenePinnow** [comment]
@cpanato 
I updated my fork again on the newest version. Can you please check and merge. I would like to update mattermost chart and would be nice if it is gitops ready.

**Comment by cpanato** [comment]
there is a lint issue

```
charts/mattermost-enterprise-edition/Chart.yaml
  40:47     error    no new line character at the end of file  (new-line-at-end-of-file)
```

also can you squash the commits?

**Comment by RenePinnow** [comment]
@cpanato 
Squashed my commits and fixed the issue.

**Comment by cpanato** [comment]
thanks @RenePinnow for the PR

I will redirect to @spirosoik and @stylianosrigas for review and to sync the merges

**Review by spirosoik — APPROVED** [review]

**Comment by RenePinnow** [comment]
@spirosoik can you please merge it?

**Review by stylianosrigas — APPROVED** [review]
Good stuff @RenePinnow 🚀

**Pull request merged**
