### PR TITLE
Added opportunity assign pods to nodes and service can be NodePort

### PR DESCRIPTION
**Pull request by demudrol**
#### Summary
* Affinity, NodeSelector and tolerations added to spec of Deployment
* NodePort choice added to Service 

#### Ticket Link
No ticket

### CODE REVIEW

**Comment by cpanato** [comment]
@demudrol hello! thanks for this PR, to move forward we need you the review the CLA and sign if you agree.

**Comment by jasonblais** [comment]
Hi @demudrol, thank you for your contribution!

Would you be open to completing the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)? We can then start the review process.

Please let us know if you have any questions. We'd be happy to clarify :)

**Comment by cpanato** [comment]
closing due to inactivity

**Pull request closed without merging**
