### PR TITLE
[MM-TE] Fixed nodeSelector, affinity, tolerations indentation

### PR DESCRIPTION
**Pull request by kairat1115**
The fix for nodeSelector, affinity, tolerations indentation.

Issue link: https://github.com/mattermost/mattermost-helm/issues/212

values-dev.yaml:
```yaml
nodeSelector:
    app: dms
tolerations:
    - key: app
      operator: Equal
      value: dms
      effect: NoExecute
```

Cutted unnecessary part.
```yaml
➜ helm template -f /tmp/aaaa/asdf/mattermost-helm/values-dev.yaml asdf . --debug
# Source: mattermost-team-edition/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      nodeSelector:
        app: dms
      tolerations:
        - effect: NoExecute
          key: app
          operator: Equal
          value: dms
```

### CODE REVIEW

**Comment by kairat1115** [comment]
@cpanato I guess I do not need to bump version in pull request.

**Comment by cpanato** [comment]
@kairat1115 yes you need, please bump the chart version

**Comment by cpanato** [comment]
@kairat1115 we merged some changes can you rebase this PR and I can review and get this merged. thanks

**Comment by spirosoik** [comment]
@kairat1115 could you please resolve the conflicts?

**Review by spirosoik — APPROVED** [review]

**Review by phoinixgrr — APPROVED** [review]

**Pull request closed without merging**
