### PR TITLE
MM-17927: Move to circleci. Use different iproute package.

### PR DESCRIPTION
**Pull request by metanerd**
https://github.com/mattermost/mattermost-server/issues/11922
Encountered docker build failing for https://github.com/mattermost/mattermost-load-test. It apt couldn't find iproute package, instead it suggested using iproute2. Then docker build succeeded.

### CODE REVIEW

**Comment by cpanato** [comment]
~I think we dont use this docker image anymore, only the one in the load-test repo.~
i see. I think we should use the dockerfile here https://github.com/mattermost/mattermost-load-test/blob/master/Dockerfile
maybe replace the file in the load-test with this one.

Also this will be better because the pipeline dont need to clone another repo

@jwilander any thoughts?

**Comment by jwilander** [comment]
Simplifying the pipeline always makes sense to me 👍 what do you think @metanerd ?

**Comment by cpanato** [comment]
then we remove the docker file from this repo and replace in the other repo

**Comment by metanerd** [comment]
I am not sure this wouldn't destroy user space. On the other hand it is also not clear to me what the benefits are from the non bundled alpine Dockerfile. 
I cannot find anything in the git commit message, why it was added.

**Pull request merged**
