### PR TITLE
Update Helm 3 comment

### PR DESCRIPTION
**Pull request by geonux**
#### Summary
Update the readme with informations regarding Helm v3 + Correct a small mistake in the naming of the chart.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-helm/issues/150

### CODE REVIEW

**Comment by cpanato** [comment]
@geonux thanks for your PR, can you please bump the chart version?

**Comment by geonux** [comment]
I only made modifications on the README file. Is it really necessary to bump the chart version ?

**Comment by cpanato** [comment]
@geonux yes

**Comment by cpanato** [comment]
@geonux can you rebase and resolve the conflict then we can merge it

**Comment by cpanato** [comment]
closing this
feel free to reopen

**Pull request closed without merging**
