### PR TITLE
remove config.json and add MM_CONFIG env (#12030)

### PR DESCRIPTION
**Pull request by jesperhansen17**
### What it does
---
- Removes configJSON object from values.yaml
- Creates MM_CONFIG environment variables
- Adds support for more MM_* environment variables
- Closes [#12030](https://github.com/mattermost/mattermost-server/issues/12030) in Mattermost Server

### CODE REVIEW

**Comment by justinegeffen** [comment]
Hi @jesperhansen17, we have [some documentation ](https://docs.mattermost.com/install/install-mmte-helm-gitlab-helm.html) for this that may need to be updated. Would you be open to taking a look at it and letting me know if you'd be able to assist? :)

**Comment by jasonblais** [comment]
Hi @jesperhansen17, thanks for your contribution! Let us know if you have any questions about the feedback above, we'd be happy to help :)

**Comment by cpanato** [comment]
@jesperhansen17 thanks for this PR, have a few things to do before we merge this
- can you bump the chart version?
- did you test this chart with an existing chart deployment? what are the breaking changes?
for example, if the user already set some config, how can he keep that? I think we need to write in the README something like we have here: https://github.com/mattermost/mattermost-helm/tree/master/charts/mattermost-enterprise-edition#4-upgrading-to-mattermost-chart-version-100

**Comment by jesperhansen17** [comment]
Hi @cpanato 

Sorry for late response, have not been able to work on it during December. Will try to fix the comments before the holidays, otherwise it will happen in January.

Back to the comments.
1. Yes, I will bump the chart version.
2. I need to test it with a running deployment and see what breaking changes that might happen. Depending on the findings I will update the readme accordingly.

**Comment by cpanato** [comment]
@jesperhansen17 thanks for your reply, no worries take your time and Merry Xmas!

**Comment by valentin-krasontovitsch** [comment]
hi @jesperhansen17 just stumbled upon this - would love to use env vars to configure mattermost.

do you think you will have time to finish this in the near future? or would you rather pass it on to someone else?

**Comment by cpanato** [comment]
closing due inactivity 
@valentin-krasontovitsch are you willing to take this change?

**Comment by valentin-krasontovitsch** [comment]
I will gladly take it, it's just gonna take a bit of time for me. gonna open a new pull request to track my efforts, hopefully shortly.

**Comment by jasonblais** [comment]
Thank you @valentin-krasontovitsch!

**Pull request closed without merging**
