### PR TITLE
Update mm-ee to 6.3.0

### PR DESCRIPTION
**Pull request by spirosoik**
#### Summary
Bump version for Mattermost Enterprise to 6.3.0

#### Ticket Link
Ticket: https://mattermost.atlassian.net/browse/DOPS-763

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
needs to be one pr per chart

**Comment by spirosoik** [comment]
@cpanato have a look again please

**Review by cpanato — APPROVED** [review]
thanks!

**Review by stylianosrigas — APPROVED** [review]
LGTM

**Pull request merged**
