### PR TITLE
Fix claimName of existing mattermost-plugins PVC

### PR DESCRIPTION
**Pull request by chapa**
This is a critical bugfix, without which it's not possible to deploy with customs *data* and *plugins* PVC.

The variable of *data* PVC claimName was used for the *plugins* PVC claimName, which causes error like : `Unable to mount volumes for pod XXX: timeout expired waiting for volumes to attach or mount for pod`.

Result of a `kubectl describe XXX` :
```
Volumes:
[...]
  mattermost-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  NAME_OF_THE_DATA_PVC
    ReadOnly:   false
  mattermost-plugins:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  NAME_OF_THE_DATA_PVC
    ReadOnly:   false
```

### CODE REVIEW

**Comment by jasonblais** [comment]
@cpanato or @stylianosrigas can you help take a look when you have the chance?

**Comment by cpanato** [comment]
@chapa Hello, thanks for this PR, can you please sign the CLA and also bump the chart version?

**Comment by chapa** [comment]
@cpanato should be ok now ;-)

**Comment by cpanato** [comment]
@chapa can you update your PR with latest master and fix the conflict? thanks!

**Pull request merged**
